In [1]:
### Grafos Homogéneos

In [2]:
import pandas as pd

In [3]:
player_df = pd.read_csv("./datasets/tbl_player.csv")
skill_df = pd.read_csv("./datasets/tbl_player_skill.csv")
team_df = pd.read_csv("./datasets/tbl_team.csv")

In [7]:
player_df = player_df[["int_player_id", "str_player_name", "str_positions", "int_overall_rating", "int_team_id"]]
skill_df = skill_df[["int_player_id", "int_long_passing", "int_ball_control", "int_dribbling"]]
team_df = team_df[["int_team_id", "str_team_name", "int_overall"]]

In [16]:
player_df = player_df.merge(skill_df, on='int_player_id')
fifa_df = player_df.merge(team_df, on='int_team_id')

In [19]:
fifa_df.columns

Index(['int_player_id', 'str_player_name', 'str_positions',
       'int_overall_rating', 'int_team_id', 'int_long_passing',
       'int_ball_control', 'int_dribbling', 'str_team_name', 'int_overall'],
      dtype='object')

In [22]:
fifa_df = fifa_df.sort_values(by="int_overall_rating", ascending=False)

In [23]:
fifa_df.head()

int_player_id                      str_player_name str_positions  \
0                1       Lionel Andrés Messi Cuccittini    RW, ST, CF   
22               2  Cristiano Ronaldo dos Santos Aveiro        ST, LW   
44               3                            Jan Oblak            GK   
88               5        Neymar da Silva Santos Júnior       LW, CAM   
114              6                   Robert Lewandowski            ST   

     int_overall_rating  int_team_id  int_long_passing  int_ball_control  \
0                  93.0          5.0                91                96   
22                 92.0          6.0                77                92   
44                 91.0          8.0                40                30   
88                 91.0          7.0                81                95   
114                91.0          4.0                70                88   

     int_dribbling        str_team_name  int_overall  
0               96         FC Barcelona           84  
22              88             Juventus           83  
44              12      Atlético Madrid           83  
88              95  Paris Saint-Germain           83  
114             85    FC Bayern München           84

In [26]:
print(max(fifa_df["int_player_id"].value_counts()))

1


In [27]:
sorted_df = fifa_df.sort_values(by="int_player_id")

In [29]:
node_features = sorted_df[["str_positions", "int_long_passing", "int_ball_control", "int_dribbling"]]

In [31]:
pd.set_option('mode.chained_assignment', None)

In [32]:
positions = node_features["str_positions"].str.split(",", expand=True)

In [35]:
node_features["str_positions"]

0       RW, ST, CF
22          ST, LW
44              GK
65         CAM, CM
88         LW, CAM
           ...    
5329            CB
3989            LB
4421            ST
5325            ST
5276       CF, CAM
Name: str_positions, Length: 5478, dtype: object

In [33]:
positions

0     1     2
0      RW    ST    CF
22     ST    LW  None
44     GK  None  None
65    CAM    CM  None
88     LW   CAM  None
...   ...   ...   ...
5329   CB  None  None
3989   LB  None  None
4421   ST  None  None
5325   ST  None  None
5276   CF   CAM  None

[5478 rows x 3 columns]

In [36]:
node_features["first_position"] = positions[0]

In [38]:
node_features = pd.concat([node_features, pd.get_dummies(node_features["first_position"])], axis=1, join='inner')

In [39]:
node_features

str_positions  int_long_passing  int_ball_control  int_dribbling  \
0       RW, ST, CF                91                96             96   
22          ST, LW                77                92             88   
44              GK                40                30             12   
65         CAM, CM                93                92             88   
88         LW, CAM                81                95             95   
...            ...               ...               ...            ...   
5329            CB                62                59             46   
3989            LB                76                60             45   
4421            ST                52                71             56   
5325            ST                62                71             69   
5276       CF, CAM                80                75             70   

     first_position  CAM  CB  CDM  CF  CM  GK  LB  LM  LW  LWB  RB  RM  RW  \
0                RW    0   0    0   0   0   0   0   0   0    0   0   0   1   
22               ST    0   0    0   0   0   0   0   0   0    0   0   0   0   
44               GK    0   0    0   0   0   1   0   0   0    0   0   0   0   
65              CAM    1   0    0   0   0   0   0   0   0    0   0   0   0   
88               LW    0   0    0   0   0   0   0   0   1    0   0   0   0   
...             ...  ...  ..  ...  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..   
5329             CB    0   1    0   0   0   0   0   0   0    0   0   0   0   
3989             LB    0   0    0   0   0   0   1   0   0    0   0   0   0   
4421             ST    0   0    0   0   0   0   0   0   0    0   0   0   0   
5325             ST    0   0    0   0   0   0   0   0   0    0   0   0   0   
5276             CF    0   0    0   1   0   0   0   0   0    0   0   0   0   

      RWB  ST  
0       0   0  
22      0   1  
44      0   0  
65      0   0  
88      0   0  
...   ...  ..  
5329    0   0  
3989    0   0  
4421    0   1  
5325    0   1  
5276    0   0  

[5478 rows x 20 columns]

In [40]:
node_features.drop(["str_positions", "first_position"], axis=1, inplace=True)

In [42]:
node_features.head() 

int_long_passing  int_ball_control  int_dribbling  CAM  CB  CDM  CF  CM  \
0                 91                96             96    0   0    0   0   0   
22                77                92             88    0   0    0   0   0   
44                40                30             12    0   0    0   0   0   
65                93                92             88    1   0    0   0   0   
88                81                95             95    0   0    0   0   0   

    GK  LB  LM  LW  LWB  RB  RM  RW  RWB  ST  
0    0   0   0   0    0   0   0   1    0   0  
22   0   0   0   0    0   0   0   0    0   1  
44   1   0   0   0    0   0   0   0    0   0  
65   0   0   0   0    0   0   0   0    0   0  
88   0   0   0   1    0   0   0   0    0   0

In [43]:
x = node_features.to_numpy()

In [44]:
x

array([[91, 96, 96, ...,  1,  0,  0],
       [77, 92, 88, ...,  0,  0,  1],
       [40, 30, 12, ...,  0,  0,  0],
       ...,
       [52, 71, 56, ...,  0,  0,  1],
       [62, 71, 69, ...,  0,  0,  1],
       [80, 75, 70, ...,  0,  0,  0]])

In [45]:
sorted_df = fifa_df.sort_values(by="int_player_id")

In [47]:
labels = sorted_df[["int_overall"]]

In [49]:
y = labels.to_numpy()

In [50]:
y

array([[84],
       [83],
       [83],
       ...,
       [71],
       [67],
       [65]])

In [51]:
fifa_df["int_player_id"] = fifa_df.reset_index().index

In [53]:
fifa_df["str_team_name"].value_counts()

Manchester United    30
Arsenal              29
Chelsea              29
Fulham               28
Everton              28
                     ..
Melbourne Victory     1
Odds BK               1
IK Sirius             1
Sunderland            1
AS Nancy Lorraine     1
Name: str_team_name, Length: 530, dtype: int64

In [54]:
import itertools
import numpy as np

teams = fifa_df["str_team_name"].unique()
all_edges = np.array([], dtype=np.int32).reshape((0, 2))
for team in teams:
    team_df = fifa_df[fifa_df["str_team_name"] == team]
    players = team_df["int_player_id"].values
    # Build all combinations, as all players are connected
    permutations = list(itertools.combinations(players, 2))
    edges_source = [e[0] for e in permutations]
    edges_target = [e[1] for e in permutations]
    team_edges = np.column_stack([edges_source, edges_target])
    all_edges = np.vstack([all_edges, team_edges])
# Convert to Pytorch Geometric format
edge_index = all_edges.transpose()
edge_index # [2, num_edges]

array([[   0.,    0.,    0., ..., 4697., 4698., 5334.],
       [  10.,   46.,   47., ..., 5354., 5354., 5340.]])

In [65]:
from torch_geometric.data import Data
data = Data(x=x, edge_index=edge_index, y=y)

In [66]:
data

Data(x=[5478, 18], edge_index=[2, 40511], y=[5478, 1])

In [67]:
import matplotlib.pyplot as plt
import networkx as nx

def visualize_graph(G, color):
    plt.figure(figsize=(7,7))
    plt.xticks([])
    plt.yticks([])
    nx.draw_networkx(G, pos=nx.spring_layout(G, seed=42), with_labels=False, node_color=color, cmap="Set2")
    plt.show()

In [68]:
from torch_geometric.utils import to_networkx

G = to_networkx(data=data, to_undirected=True)
visualize_graph(G, color=data.y)

/home/claudio/anaconda3/lib/python3.9/site-packages/torch_geometric/data/storage.py:261: UserWarning: Unable to accurately infer 'num_nodes' from the attribute set '{'edge_index', 'x', 'y'}'. Please explicitly set 'num_nodes' as an attribute of 'data' to suppress this warning
  warnings.warn(


TypeError: 'NoneType' object cannot be interpreted as an integer